baseurl: "/"
title: "Stackbit Ampersand Theme"
page_load_js: "assets/js/main.js"
params:
  header:
    title: "Ampersand"
    logo_img: images/logo.png
    has_nav: true
  footer:
    content: "&copy; All rights reserved."
    links:
      - text: Made with Stackbit
        url: https://www.stackbit.com
        new_window: true
    has_social: true
  layout_style: grid
  palette: green
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
